version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/url_db
      - REDIS_URL=redis://redis:6379
    command: >
      sh -c "
        ./wait-for-db.sh && 
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: url_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
