"""create url_shorteners table

Revision ID: 3d86845b3cce
Revises: 
Create Date: 2025-05-04 18:59:41.416678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d86845b3cce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_shorteners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=True),
    sa.Column('shortened_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shortened_url')
    )
    op.create_index(op.f('ix_url_shorteners_id'), 'url_shorteners', ['id'], unique=False)
    op.create_index(op.f('ix_url_shorteners_original_url'), 'url_shorteners', ['original_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_shorteners_original_url'), table_name='url_shorteners')
    op.drop_index(op.f('ix_url_shorteners_id'), table_name='url_shorteners')
    op.drop_table('url_shorteners')
    # ### end Alembic commands ###
