"""change is_active to boolean and add clicks field

Revision ID: be3966950db7
Revises: 3d86845b3cce
Create Date: 2025-05-05 07:02:48.724953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3966950db7'
down_revision: Union[str, None] = '3d86845b3cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_url_shorteners_id', table_name='url_shorteners')
    op.drop_index('ix_url_shorteners_original_url', table_name='url_shorteners')
    op.drop_table('url_shorteners')
    # op.add_column('urls', sa.Column('clicks', sa.Integer(), nullable=True))
    op.alter_column(
        'urls',
        'is_active',
        existing_type=sa.Integer(),
        type_=sa.Boolean(),
        postgresql_using='is_active::boolean'
    )
    op.add_column('urls', sa.Column('clicks', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('urls', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('urls', 'clicks')
    op.create_table('url_shorteners',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shortened_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='url_shorteners_pkey'),
    sa.UniqueConstraint('shortened_url', name='url_shorteners_shortened_url_key')
    )
    op.create_index('ix_url_shorteners_original_url', 'url_shorteners', ['original_url'], unique=False)
    op.create_index('ix_url_shorteners_id', 'url_shorteners', ['id'], unique=False)
    # ### end Alembic commands ###
